### ISSUE TITLE
Small file size tooltip appears in other places

### ISSUE THREAD

**Issue by SpiralGalaxy** [Rambalac/AmazonCloudDriveApi#12]
The small file type tooltip (Maximum size of files which will be cached whole on first request.) that appears overs "Small files size, Mb" also appears when you hover over "Small files cache, Mb", "Files download" and "Files uploading"

While I am here, can you explain the purpose of the small files cache? Does that have anything to do with uploading or is that just something like a quick access feature for files already backed up?

**Comment by Rambalac** [comment]
"Small files" are fast because downloaded whole to disk and can be updated. It allows to use small files in usual application. Big files are cached in memory and they are much slower, but still accessible in some applications like Windows explorer.
All files will be uploaded if they are just written whole. If file is big and applications try to update different parts after writing it they can fail. 
I'm still slowly trying to improve it to eliminate this separation and make file updating working correctly for any file, but it's a bit too complicated for me.
