### ISSUE TITLE
Run as a Service

### ISSUE THREAD

**Issue by exilewolf** [Rambalac/AmazonCloudDriveApi#16]
Hi there!

Unreal tool, Is there a way that this can be run as a service ? so it can be used with Tasks ? This is for ADC Dokan.Net

**Comment by Rambalac** [comment]
Is it about library or Amazon Cloud Drive disk app? 
If it'is about app it's here https://github.com/Rambalac/ACDDokanNet and it because you created issue here it's "a bit" outdated. 
Because of some features are user profile dependent it cannot be Windows Service because services usually work in special accounts.
