### ISSUE TITLE
Invalid Scope

### ISSUE THREAD

**Issue by NebulaSleuth** [Rambalac/AmazonCloudDriveApi#26]
I may not I have not setup my security key properly, but I keep getting a response of:
'error_description=An+unknown+scope+was+requested&error=invalid_scope'
Where/How does one authorize Amazon Drive Scopes for a given security key?

**Comment by Rambalac** [comment]
It should be in Amazon Dev console in Security Profile whitelist. Not should if it's possible after August.

**Comment by Rambalac** [comment]
Actually there is no Drive in Dev console anymore.

**Comment by Kyrodan** [comment]
Just a comment from an individual developer with a small desktop app:
You have to apply for API-Access and it seems it always gets denied if 
* you are an individual developer
* you build a desktop app
You also have to let your app reviewed by Amazon prior releasing (which takes several weeks!), communication is very frustating.
I have problems for month, so ACD is not an option for me anymore: I have no approval for my App since start of August and got an email, that it takes some more time. Very frustrating.

**Comment by Rambalac** [comment]
Yeah, I'm ready to get email from Amazon about my security ID suspension any day.

**Comment by Rambalac** [comment]
I believe this can be closed
